const ProjectData = [
    {
        "id":1,
        "name":"Creative Agency",
        "live":"https://creative-agency-43a64.web.app/",
        "github":"https://github.com/ibrahimkhalilhimu/creative-agency",
        "img":"https://i.ibb.co/qD6LRF9/creative.png",
        "description":"This is a React web app.This side had technology used react js, react router, node js,express js,mongodb,firebase,bootstrap",
    },
    {
        "id":2,
        "name":"StoreFront",
        "live":"https://fresh-valley-2fc07.web.app/",
        "github":"https://github.com/ibrahimkhalilhimu/fresh-valley",
        "img":"https://i.ibb.co/hVQZXwZ/Screenshot-2021-04-01-203736.png",
        "description":"This is a React web app.This side had technology used react js, react router, node js,express js,mongodb,firebase,bootstrap",
    },
    {
        "id":3,
        "name":"Volunteer Network",
        "live":"https://valunteer-48ea4.web.app/",
        "github":"https://github.com/ibrahimkhalilhimu/valunteer",
        "img":"https://i.ibb.co/NrzN5fQ/volunteer.png",
        "description":"This is a React web app.This side had technology used react js, react router, node js,express js,mongodb,firebase,bootstrap",
    },
    {
        "id":4,
        "name":"Urban Raiders",
        "live":"https://urban-riders-86c5e.web.app/",
        "github":"https://github.com/ibrahimkhalilhimu/urban-riders",
        "img":"https://i.ibb.co/c2ktRD1/Screenshot-2021-03-21-151704.png",
        "description":"This is a React web app.This side had technology used react js, react router,firebase,bootstrap",
    },
    {
        "id":5,
        "name":"Travel Guru",
        "live":"https://travel-guru-2448c.web.app/",
        "github":"https://github.com/ibrahimkhalilhimu/travel-guru",
        "img":"https://i.ibb.co/yyw8WCD/Screenshot-2.png",
        "description":"This is a React web app.This side had technology used react js, react router,firebase,bootstrap",
    },
    {
        "id":6,
        "name":"Airbnb",
        "live":"https://arbnb.netlify.app/",
        "github":"https://github.com/ibrahimkhalilhimu/airbnb-clone",
        "img":"https://i.ibb.co/D7DmYST/Screenshot-arbnb.png",
        "description":"This side is react web responsive page.This side used react js,css,material ui,react-router,date-picker",
    },
    {
        "id":7,
        "name":"DSI Landing page",
        "live":"https://dsl-landing-page.netlify.app/",
        "github":"https://github.com/ibrahimkhalilhimu/dsi-landing-page",
        "img":"https://i.ibb.co/0hTFy4v/Screenshot-2021-03-24-224348.png",
        "description":"This side is react web responsive page.This side used react js,css,bootstrap",
    },
    {
        "id":8,
        "name":"Jaket Responsive",
        "live":"https://jaket-responsive.netlify.app/",
        "github":"https://github.com/ibrahimkhalilhimu/jaket-responsive",
        "img":"https://i.ibb.co/9v57Jb2/jaket-Responsive.png",
        "description":"This side is react web responsive page.This side used react js,css,bootstrap",
    },
    {
        "id":9,
        "name":"Online Course",
        "live":"https://kind-meitner-075fb0.netlify.app/",
        "github":"https://github.com/ibrahimkhalilhimu/online-course",
        "img":"https://i.ibb.co/s5GysrN/omline-course.png",
        "description":"This side is react web page.This side used react js,react router,bootstrap",
    },

 
    {
        "id":10,
        "name":"E-School",
        "live":"https://ibrahimkhalilhimu.github.io/e-school/",
        "github":"https://github.com/ibrahimkhalilhimu/e-school",
        "img":"https://i.ibb.co/wLhZbt4/e-school.png",
        "description":"This is a Html css website. Technology use Html,css,Bootstrap",
    },    {
        "id":11,
        "name":"Friends Bank",
        "live":"https://ibrahimkhalilhimu.github.io/FRIENDSbANK/",
        "github":"https://github.com/ibrahimkhalilhimu/FRIENDSbANK",
        "img":"https://i.ibb.co/wKK0Xqp/friends-Bank.png",
        "description":"This is a vanila Javascript side.This side use html,css,and javaScript.",
    },
    {
        "id":12,
        "name":"Ema-Jhon",
        "live":"https://ema-jhon-simple-650c4.web.app/",
        "github":"https://github.com/ibrahimkhalilhimu/ema-john-simple",
        "img":"https://i.ibb.co/3mqHLBK/ema-jhon.png",
        "description":"This side technology used react js,node js,express js,mongodb,firebase,bootstrap",
    },
 
    {
        "id":13,
        "name":"Social-Buddy",
        "live":"https://amazing-clarke-09ee2b.netlify.app/",
        "github":"https://github.com/ibrahimkhalilhimu/social-buddy-react-router",
        "img":"https://i.ibb.co/dkg1K59/social-buddy.png",
        "description":"Technology used React js,Rest api,bootstrap",
    },
    {
        "id":14,
        "name":"Cooking-Master",
        "live":"https://ibrahimkhalilhimu.github.io/cooking-master/",
        "github":"https://github.com/ibrahimkhalilhimu/cooking-master",
        "img":"https://i.ibb.co/KjBn25q/cooking-master.png",
        "description":"This is Javascript Search Qurray",
    },
  
 
]
export default ProjectData